Deterministic build: Fix typing-extensions version requirement
The upgrade to trezor 0.12 did not satisfy all its dependencies:

ERROR: trezor 0.12.0 has requirement typing-extensions>=3.7.4, but
you'll have typing-extensions 3.7.2 which is incompatible.

This upgrades typing-extensions to the latest version, 3.7.4.2.