websockets (electrum-merchant): fix stale/old code which no longer runs
I am unable to test this locally so I hope these changes fix things --
we had a user trying to set this up and he complained of the following
stack trace:

Traceback (most recent call last):
  File "/home/james/Electron-Cash/lib/util.py", line 790, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/home/james/Electron-Cash/lib/websockets.py", line 109, in run
    addr = self.network.h2addr.get(h, None)
AttributeError: 'Network' object has no attribute 'h2addr'

This commit hopefully fixes things.