electrum-env script: fix instructions for -hw deps
--no-deps is needed since the introduction of ghost.txt
(ref commit 74615623ebb23b3a772e3ca2e9ba5167590c8c1f)

```
Collecting platformdirs>=4.4.0 (from trezor==0.20.1->-r contrib/deterministic-build/requirements-hw.txt (line 486))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    platformdirs>=4.4.0 from https://files.pythonhosted.org/packages/19/a9/c34aebedd3a4c9afe5101b1b8713710b3fec18087c8a36c35d2f909861bd/platformdirs-4.11.3-py3-none-any.whl (from trezor==0.20.1->-r contrib/deterministic-build/requirements-hw.txt (line 486))
```