macos build: fix missing keepkeylib
```
  9.76 | D | plugins.keepkey.qt.Plugin | error importing keepkeylib
Traceback (most recent call last):
  File "electrum/plugins/keepkey/keepkey.py", line 77, in __init__
    from . import client
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "electrum/plugins/keepkey/client.py", line 1, in <module>
    from .keepkeylib.keepkeylib.client import proto, BaseClient, ProtocolMixin
ModuleNotFoundError: No module named 'electrum.plugins.keepkey.keepkeylib.keepkeylib'
```