Follow-up to #1541 pt. II - fix bug introduced by import locale
Now we need to specify that as a package to setup.py, otherwise
AppImage, Wine, and OSX builds crash with a stach track:

 LOCALE_DIR = os.path.dirname(locale.__file__)
AttributeError: module 'electroncash.locale' has no attribute '__file__'

I TOLD him to use __path__.. but NOOOO. He's a strong-willed one, he is.
:)