QT: Only set if hasattr(QtCore.Qt, "AA_ShareOpenGLContexts")
If the attribute does not exist (presumably in older versions of Qt),
this change prevents the following error:

  AttributeError: type object 'Qt' has no attribute 'AA_ShareOpenGLContexts'