plugin: trezor: handle empty passphrase feature in settings dialog
The settings dialog would raise after disabling the passphrase because
the feature is None after disconnecting:

```
 24.43 | I | plugins.trezor.clientbase.TrezorClientBase | locking: <trezorlib.protocol_v1.TrezorClientV1 object at 0x7fec5f7d45e0>
 24.82 | I | plugins.trezor.clientbase.TrezorClientBase | closing: SessionV1(id=fec9fa77e94f52faa50e3aa5573d6e760a028e2e6cd2366bc998dcc9870f2382)
 24.97 | E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/var/home/user/code/code_vm/electrum-3/electrum/gui/common_qt/util.py", line 175, in on_done
    cb_result(result)
    ~~~~~~~~~^^^^^^^^
  File "/var/home/user/code/code_vm/electrum-3/electrum/plugins/trezor/qt.py", line 534, in update
    passphrases_label.setText(disen[features.passphrase_protection])
                              ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not NoneType
```