qt: fix onchain invoice dialog exc for script outputs
Fixes exception when double clicking on saved invoice (`show_onchain_invoice()`)
for an invoice containing a script output (invoice.address is None).

```
 17.57 | E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/var/home/user/code/code_vm/electrum/electrum/gui/qt/my_treeview.py", line 341, in mouseDoubleClickEvent
    self.on_double_click(idx)
    ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/var/home/user/code/code_vm/electrum/electrum/gui/qt/invoice_list.py", line 88, in on_double_click
    self.show_invoice(key)
    ~~~~~~~~~~~~~~~~~^^^^^
  File "/var/home/user/code/code_vm/electrum/electrum/gui/qt/invoice_list.py", line 150, in show_invoice
    self.main_window.show_onchain_invoice(invoice)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/var/home/user/code/code_vm/electrum/electrum/gui/qt/main_window.py", line 1672, in show_onchain_invoice
    outputs_str = '\n'.join(map(lambda x: x.address + ' : ' + self.format_amount(x.value)+ self.base_unit(), invoice.outputs))
  File "/var/home/user/code/code_vm/electrum/electrum/gui/qt/main_window.py", line 1672, in <lambda>
    outputs_str = '\n'.join(map(lambda x: x.address + ' : ' + self.format_amount(x.value)+ self.base_unit(), invoice.outputs))
                                          ~~~~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```