contrib/make_download: fix imports
not sure why this was not an issue before(?)
perhaps due to python version differences
```
$ ./contrib/make_download /home/user/wspace/electrum-web
Traceback (most recent call last):
  File "/home/user/wspace/electrum/./contrib/make_download", line 17, in <module>
    version_spec = importlib.util.spec_from_file_location('version', 'electrum/version.py')
                   ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'
```