contrib/add_cosigner: fix for python 3.13
This script used to work, I assume my breakage is due to the python version.

```
Traceback (most recent call last):
File "/home/user/wspace/electrum/./contrib/add_cosigner", line 35, in <module>
    version_spec = importlib.util.spec_from_file_location('version', 'electrum/version.py')
                ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'
```