swapserver: cli: skip pending swaps in history commands
skip pending swaps in the swapserver history/summary cli commands.
They are not relevant and don't contain all required informations yet.

Fixes https://github.com/spesmilo/electrum/issues/10521
Fixes https://github.com/spesmilo/electrum/issues/10525

```
 File "/home/electrum/electrum-fork/electrum/daemon.py", line 268, in handle
   response['result'] = await f(*params)
                        ^^^^^^^^^^^^^^^^
 File "/home/electrum/electrum-fork/electrum/daemon.py", line 381, in run_cmdline
   result = await func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/electrum/electrum-fork/electrum/commands.py", line 207, in func_wrapper
 File "/home/electrum/electrum-fork/electrum/commands.py", line 2349, in func_wrapper
   group = parser.add_argument_group('network options')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/electrum/electrum-fork/electrum/plugins/swapserver/__init__.py", line 79, in get_summary
   swap_history = await get_history(self)
                  ^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/electrum/electrum-fork/electrum/commands.py", line 207, in func_wrapper
 File "/home/electrum/electrum-fork/electrum/commands.py", line 2349, in func_wrapper
   group = parser.add_argument_group('network options')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/electrum/electrum-fork/electrum/plugins/swapserver/__init__.py", line 60, in get_history
   'date': swap['date'].strftime("%Y-%m-%d"),
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strftime'
```