ci: builds: android: fix cache key
Fix the cache key of the scheduled Android CI build which failed
at the `Cache buildozer (p4a)` step with the following error:
```
Error: The template is not valid. .github/workflows/builds.yml (Line: 113, Col: 16): hashFiles('contrib/android/**') failed. Fail to hash files under directory '/home/runner/work/electrum/electrum'
```

Probably it failed because the `contrib/android/.cache` directory
got included in the cache key, which worked on Cirrus.
This specifies the cache key hash inputs explicitly.