build: appimage: fix build: bump alpine apk deps
note: magic incantation to clear relevant docker build cache:
```
$ docker builder prune --all
```

build log:
```
$ ./contrib/build-linux/appimage/build.sh
[...]
 => ERROR [2/6] RUN apk add --no-cache     bash=5.2.37-r0     alpine-sdk=1.1-r0     util-linux=2.40.4-r1     strace=6.12-r0     file=5.46-r2     autoconf=2.72-r0     automake=1.17-r0     libtool=2.4.7-r3     xz=5.6.3-r1     eudev-dev=3.2.14-r5     gettext-  0.6s
------
 > [2/6] RUN apk add --no-cache     bash=5.2.37-r0     alpine-sdk=1.1-r0     util-linux=2.40.4-r1     strace=6.12-r0     file=5.46-r2     autoconf=2.72-r0     automake=1.17-r0     libtool=2.4.7-r3     xz=5.6.3-r1     eudev-dev=3.2.14-r5     gettext-dev=0.22.5-r0     linux-headers=6.6-r1     meson=1.6.1-r0     zstd-dev=1.5.6-r2     zstd-static=1.5.6-r2     zlib-dev=1.3.2-r0     zlib-static=1.3.2-r0     clang19=19.1.4-r0     musl-dev=1.2.5-r11     mimalloc2-dev=2.1.7-r0:
0.224 fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz
0.309 fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz
0.475 ERROR: unable to select packages:
0.476   xz-5.8.3-r0:
0.476     breaks: world[xz=5.6.3-r1]
0.476     satisfies: gettext-dev-0.22.5-r0[xz]
------
Dockerfile:4
--------------------
   3 |     # includes dependencies from https://git.alpinelinux.org/aports/tree/main/fuse3/APKBUILD
   4 | >>> RUN apk add --no-cache \
   5 | >>>     bash=5.2.37-r0 \
   6 | >>>     alpine-sdk=1.1-r0 \
   7 | >>>     util-linux=2.40.4-r1 \
   8 | >>>     strace=6.12-r0 \
   9 | >>>     file=5.46-r2 \
  10 | >>>     autoconf=2.72-r0 \
  11 | >>>     automake=1.17-r0 \
  12 | >>>     libtool=2.4.7-r3 \
  13 | >>>     xz=5.6.3-r1 \
  14 | >>>     eudev-dev=3.2.14-r5 \
  15 | >>>     gettext-dev=0.22.5-r0 \
  16 | >>>     linux-headers=6.6-r1 \
  17 | >>>     meson=1.6.1-r0 \
  18 | >>>     zstd-dev=1.5.6-r2 \
  19 | >>>     zstd-static=1.5.6-r2 \
  20 | >>>     zlib-dev=1.3.2-r0 \
  21 | >>>     zlib-static=1.3.2-r0 \
  22 | >>>     clang19=19.1.4-r0 \
  23 | >>>     musl-dev=1.2.5-r11 \
  24 | >>>     mimalloc2-dev=2.1.7-r0
  25 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache     bash=5.2.37-r0     alpine-sdk=1.1-r0     util-linux=2.40.4-r1     strace=6.12-r0     file=5.46-r2     autoconf=2.72-r0     automake=1.17-r0     libtool=2.4.7-r3     xz=5.6.3-r1     eudev-dev=3.2.14-r5     gettext-dev=0.22.5-r0     linux-headers=6.6-r1     meson=1.6.1-r0     zstd-dev=1.5.6-r2     zstd-static=1.5.6-r2     zlib-dev=1.3.2-r0     zlib-static=1.3.2-r0     clang19=19.1.4-r0     musl-dev=1.2.5-r11     mimalloc2-dev=2.1.7-r0" did not complete successfully: exit code: 2
🗯 ERROR: Error building type2-runtime.
```